name: Python Autograder

on:
  pull_request:
    paths:
      - "grade.py"
  push:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Use your desired Python version

      # Run the autograder script
      - name: Run autograder
        run: |
          python grade.py  # Make sure grade.py is running correctly and generates results.json

      # Upload the results.json file as an artifact
      - name: Upload results.json
        uses: actions/upload-artifact@v4
        with:
          name: results
          path: results.json